fuxi_schemas = {
    "seed_bank_info": {
        "introduction": "种子库管理表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 50, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 50, "introduction": ""},
            {"title": "variety", "type": "varchar", "length": 50, "introduction": "品种"},
            {"title": "variety_alias", "type": "varchar", "length": 50, "introduction": "品种别名"},
            {"title": "variety_code", "type": "varchar", "length": 50, "introduction": "统一编号"},
            {"title": "crop_name", "type": "varchar", "length": 50, "introduction": "作物名称"},
            {"title": "listing_date", "type": "timestamp", "length": 6, "introduction": "上市日期"},
            {"title": "growth_cycle", "type": "varchar", "length": 50, "introduction": "生长周期/生育期/生长日期"},
            {"title": "breeding_institute", "type": "varchar", "length": 50, "introduction": "育种机构"},
            {"title": "seeding_rate", "type": "numeric", "length": 0, "introduction": "亩播量 kg/亩"},
            {"title": "variety_attribute", "type": "text", "length": 0, "introduction": "品种属性"},
            {"title": "neatness", "type": "numeric", "length": 0, "introduction": "净度"},
            {"title": "budding_rate", "type": "numeric", "length": 0, "introduction": "出芽率"},
            {"title": "emergence_rate", "type": "numeric", "length": 0, "introduction": "出苗率"},
            {"title": "water_content", "type": "numeric", "length": 0, "introduction": "水分含量"},
            {"title": "suitable_area", "type": "jsonb", "length": 0, "introduction": "适宜区域"},
            {"title": "previous_crop", "type": "varchar", "length": 255, "introduction": "适合上一茬作物"},
            {"title": "plant_years", "type": "int2", "length": 16, "introduction": "已种植年份"},
            {"title": "total_sown_area", "type": "numeric", "length": 0, "introduction": "累计播种面积（万亩）"},
            {"title": "year_sown_area", "type": "numeric", "length": 0, "introduction": "年播种面积（万亩）"},
            {"title": "average_yield", "type": "numeric", "length": 0, "introduction": "平均亩产（kg/亩）"},
            {"title": "info_type", "type": "varchar", "length": 2, "introduction": "信息状态 1 待提交  2 已完成"}
        ]
    },
    "seed_bank_attribute":{
        "introduction": "种子库管理表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 50, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 50, "introduction": ""},
            {"title": "seed_bank_attribute", "type": "varchar", "length": 50, "introduction": "种子库字段属性"},
            {"title": "field_name", "type": "varchar", "length": 255, "introduction": "字段名称"},
            {"title": "field_type", "type": "varchar", "length": 20, "introduction": "字段类型"},
            {"title": "field_content", "type": "text", "length": 0, "introduction": "字段内容"},
            {"title": "field_unit", "type": "varchar", "length": 255, "introduction": "字段单位"},
            {"title": "remarks", "type": "varchar", "length": 255, "introduction": "备注"},
            {"title": "value1", "type": "varchar", "length": 255, "introduction": "值1"},
            {"title": "value2", "type": "varchar", "length": 255, "introduction": "值2"},
            {"title": "value3", "type": "varchar", "length": 255, "introduction": "值3"},
            {"title": "value4", "type": "varchar", "length": 255, "introduction": "值4"},
            {"title": "value5", "type": "varchar", "length": 255, "introduction": "值5"},
            {"title": "value6", "type": "varchar", "length": 255, "introduction": "值6"}
        ]
    },
    "seed_bank_value": {
        "introduction": "种子库播种/生长周期条件表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "", "length": 0, "introduction": "创建时间"},
            {"title": "update_time", "type": "", "length": 0, "introduction": "修改时间"},
            {"title": "create_user", "type": "varchar", "length": 50, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 50, "introduction": ""},
            {"title": "seed_bank_attribute", "type": "varchar", "length": 255, "introduction": "种子库字段属性"},
            {"title": "field_name", "type": "varchar", "length": 255, "introduction": "字段名称"},
            {"title": "field_type", "type": "varchar", "length": 20, "introduction": "字段类型"},
            {"title": "field_content", "type": "text", "length": 0, "introduction": "字段内容"},
            {"title": "field_unit", "type": "varchar", "length": 50, "introduction": "字段单位"},
            {"title": "remarks", "type": "varchar", "length": 255, "introduction": "备注"},
            {"title": "value1", "type": "varchar", "length": 255, "introduction": "值1"},
            {"title": "value2", "type": "varchar", "length": 255, "introduction": "值2"},
            {"title": "value3", "type": "varchar", "length": 255, "introduction": "值3"},
            {"title": "value4", "type": "varchar", "length": 255, "introduction": "值4"},
            {"title": "value5", "type": "varchar", "length": 255, "introduction": "值5"},
            {"title": "value6", "type": "varchar", "length": 255, "introduction": "值6"},
            {"title": "seed_info_id", "type": "int4", "length": 32, "introduction": "种子库信息表id"},
            {"title": "seed_condition_type", "type": "varchar", "length": 5, "introduction": "条件类型 01播种条件  02生长周期条件"},
            {"title": "seed_condition_id", "type": "int4", "length": 32, "introduction": "种子生长周期条件表id"},
            {"title": "field_id", "type": "int4", "length": 32, "introduction": "种子库字段属性id"}
        ]
    },
    "seed_growthcycle_condition": {
        "introduction": "种子生长周期条件表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "", "length": 0, "introduction": ""},
            {"title": "update_time", "type": "", "length": 0, "introduction": ""},
            {"title": "create_user", "type": "", "length": 0, "introduction": ""},
            {"title": "update_user", "type": "", "length": 0, "introduction": ""},
            {"title": "growth_stage_name", "type": "", "length": 0, "introduction": "生长阶段名称"},
            {"title": "growth_stage_cycle", "type": "", "length": 0, "introduction": "生长阶段周期"},
            {"title": "growth_stage_pic", "type": "", "length": 0, "introduction": "生长阶段照片"},
            {"title": "seed_info_id", "type": "", "length": 0, "introduction": "种子库信息表id(品种id)"},
            {"title": "index", "type": "", "length": 0, "introduction": ""},
            {"title": "stage_start_time", "type": "", "length": 0, "introduction": ""},
            {"title": "stage_end_time", "type": "", "length": 0, "introduction": ""}
        ]
    },
    "accurate_execute_task_info": {
    "introduction": "精准执行任务信息表",
    "fields": [
      {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
      {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
      {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
      {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
      {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
      {"title": "province", "type": "varchar", "length": 15, "introduction": "省"},
      {"title": "city", "type": "varchar", "length": 15, "introduction": "市"},
      {"title": "district", "type": "varchar", "length": 15, "introduction": "县"},
      {"title": "town", "type": "varchar", "length": 15, "introduction": "乡/镇"},
      {"title": "remarks", "type": "varchar", "length": 255, "introduction": "备注"},
      {"title": "accurate_task_type", "type": "varchar", "length": 15, "introduction": "任务类型"},
      {"title": "business_entity_id", "type": "Int4", "length": 32, "introduction": "地块所属经营主体"},
      {"title": "plot_code", "type": "varchar", "length": 5, "introduction": "关联地块"},
      {"title": "agri_machine_id", "type": "Int4", "length": 32, "introduction": "匹配农机"},
      {"title": "agri_tool_id", "type": "Int4", "length": 32, "introduction": "匹配农具"},
      {"title": "formulation_id", "type": "", "length": 0, "introduction": "匹配配方"},
      {"title": "task_start_time", "type": "timestamp", "length": 6, "introduction": "任务开始时间"},
      {"title": "task_end_time", "type": "timestamp", "length": 0, "introduction": "任务结束时间"},
      {"title": "row_spacing", "type": "numeric", "length": 6, "introduction": "株距(mm)"},
      {"title": "seeding_rate", "type": "numeric", "length": 0, "introduction": "亩均播量(kg)"},
      {"title": "prescription_map_id", "type": "Int4", "length": 32, "introduction": "匹配处方图"},
      {"title": "business_entity_type", "type": "", "length": 0, "introduction": "地块所属经营主体类型"},
      {"title": "item_id", "type": "Int4", "length": 32, "introduction": "所属项目"},
      {"title": "task_exec_state", "type": "", "length": 0, "introduction": "执行状态"},
      {"title": "water_source_id", "type": "Int4", "length": 32, "introduction": "匹配水源"},
      {"title": "water_canal_id", "type": "Int4", "length": 32, "introduction": "匹配水渠"},
      {"title": "water_valve_id", "type": "Int4", "length": 32, "introduction": "匹配水阀"},
      {"title": "drainage_pump_id", "type": "Int4", "length": 32, "introduction": "匹配排水泵"},
      {"title": "prescription_type", "type": "varchar", "length": 5, "introduction": "处方图类型"},
      {"title": "prescription_create_time", "type": "timestamp", "length": 6, "introduction": "处方图生成时间"},
      {"title": "work_speed", "type": "numeric", "length": 0, "introduction": "速度(m/s)"},
      {"title": "soil_preparation_depth", "type": "numeric", "length": 0, "introduction": "耕地深度(mm)"},
      {"title": "broken_soil", "type": "numeric", "length": 0, "introduction": "碎土质量(mm)"},
      {"title": "average_usage", "type": "numeric", "length": 0, "introduction": "亩均用量(kg)"},
      {"title": "missed_rate", "type": "numeric", "length": 0, "introduction": "漏*率(%)"},
      {"title": "repeat_rate", "type": "numeric", "length": 0, "introduction": "重*率(%)"},
      {"title": "spray_pressure", "type": "numeric", "length": 0, "introduction": "喷药压力(pa)"},
      {"title": "spray_flow_rate", "type": "numeric", "length": 0, "introduction": "喷药流量(ml/s)"},
      {"title": "water_level", "type": "numeric", "length": 0, "introduction": "水位(cm)"},
      {"title": "soil_humidity", "type": "numeric", "length": 0, "introduction": "土壤湿度（%）"},
      {"title": "above_height", "type": "numeric", "length": 0, "introduction": "高度(mm)"},
      {"title": "environment_temperature_min", "type": "numeric", "length": 0, "introduction": "最小温度(℃)"},
      {"title": "environment_temperature_max", "type": "numeric", "length": 0, "introduction": "最大温度(℃)"},
      {"title": "environment_humidity_min", "type": "numeric", "length": 0, "introduction": "最小湿度(%)"},
      {"title": "environment_humidity_max", "type": "numeric", "length": 0, "introduction": "最大湿度(%)"},
      {"title": "crop_name", "type": "varchar", "length": 50, "introduction": "作物名称"},
      {"title": "crop_variety", "type": "varchar", "length": 50, "introduction": "品种"},
      {"title": "average_usage_mu", "type": "numeric", "length": 0, "introduction": "方案亩用量（公斤）"},
      {"title": "prescription_map_name", "type": "varchar", "length": 100, "introduction": ""}
    ]
  },
    "accurate_execute_task_formulation": {
    "introduction": "精准执行任务配方信息等关联表",
    "fields": [
      {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
      {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
      {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
      {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
      {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
      {"title": "accurate_task_id", "type": "Int4", "length": 32, "introduction": "任务id"},
      {"title": "formulation_id", "type": "Int4", "length": 32, "introduction": "配方id"},
      {"title": "material_id", "type": "Int4", "length": 32, "introduction": "物资id"},
      {"title": "item_id", "type": "Int4", "length": 32, "introduction": "所属项目id"},
      {"title": "remark", "type": "varchar", "length": 255, "introduction": "备注"},
      {"title": "average_usage_mu", "type": "numeric", "length": 0, "introduction": "亩用量（公斤/g/kg/升）"},
      {"title": "material_type", "type": "varchar", "length": 255, "introduction": "物资类型 1农药  2肥料"}
    ]
  },
    "agri_analysis_report":{
        "introduction": "农情分析报告表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "item_id", "type": "int4", "length": 32, "introduction": ""},
            {"title": "report_create_type", "type": "varchar", "length": 5, "introduction": "生成方式 1 一键生成  2 自动生成"},
            {"title": "remarks", "type": "varchar", "length": 255, "introduction": ""},
            {"title": "file_id", "type": "varchar", "length": 50, "introduction": ""}
        ]
    },
    "agricultural": {
        "introduction": "农机信息表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "license_number", "type": "varchar", "length": 100, "introduction": "车牌号"},
            {"title": "terminal_encoding", "type": "varchar", "length": 20, "introduction": "终端编码"},
            {"title": "description", "type": "varchar", "length": 255, "introduction": "备注"},
            {"title": "status", "type": "varchar", "length": 10, "introduction": "状态 0启用 1禁用"},
            {"title": "vehicle_type", "type": "varchar", "length": 20, "introduction": "车辆类型"},
            {"title": "ability_to_drive", "type": "varchar", "length": 10, "introduction": "能否远程驾驶"},
            {"title": "business_and_use_id", "type": "int4", "length": 32, "introduction": "所属经营使用主体"},
            {"title": "network_status", "type": "varchar", "length": 50, "introduction": "入网状态"},
            {"title": "brand", "type": "varchar", "length": 50, "introduction": "品牌"},
            {"title": "model", "type": "varchar", "length": 50, "introduction": "型号"},
            {"title": "power", "type": "varchar", "length": 50, "introduction": "功率"},
            {"title": "fuel", "type": "varchar", "length": 50, "introduction": "油耗"},
            {"title": "maximum", "type": "numeric", "length": 0, "introduction": "最大速度"},
            {"title": "original_value", "type": "numeric", "length": 0, "introduction": "原值"},
            {"title": "photo", "type": "varchar", "length": 50, "introduction": "照片"},
            {"title": "item_id", "type": "int4", "length": 32, "introduction": "所属项目"},
            {"title": "last_time", "type": "timestamp", "length": 6, "introduction": "最后在线时间"},
            {"title": "business_and_use_name", "type": "varchar", "length": 50, "introduction": "名称"},
            {"title": "business_and_use_type", "type": "varchar", "length": 50, "introduction": "类型"},
            {"title": "energy_type", "type": "varchar", "length": 50, "introduction": "能源类型"},
            {"title": "deplete", "type": "numeric", "length": 0, "introduction": "消耗"},
            {"title": "deplete_two", "type": "numeric", "length": 0, "introduction": ""},
            {"title": "battery_life", "type": "varchar", "length": 50, "introduction": ""},
            {"title": "job_accuracy", "type": "varchar", "length": 50, "introduction": ""},
            {"title": "carbon_emissions", "type": "varchar", "length": 50, "introduction": "牵引力"},
            {"title": "tensile", "type": "varchar", "length": 50, "introduction": ""},
            {"title": "longitude", "type": "numeric", "length": 0, "introduction": ""},
            {"title": "latitude", "type": "numeric", "length": 0, "introduction": ""},
            {"title": "online", "type": "", "length": 0, "introduction": "在线状态（0：在线 1离线 2故障）"}
        ]
    },
    "agricultural_info": {
        "introduction": "农资信息表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "agricultural_name", "type": "varchar", "length": 255, "introduction": "农资名称"},
            {"title": "agricultural_type", "type": "varchar", "length": 255, "introduction": "农资类型"},
            {"title": "agricultural_detail", "type": "varchar", "length": 255, "introduction": "农资详情"},
            {"title": "factory", "type": "varchar", "length": 255, "introduction": "生产厂家"},
            {"title": "price", "type": "numeric", "length": 0, "introduction": "单价"},
            {"title": "inbound_num", "type": "numeric", "length": 0, "introduction": "入库数量"},
            {"title": "date_of_purchase", "type": "varchar", "length": 255, "introduction": "采购日期"},
            {"title": "item_id", "type": "varchar", "length": 255, "introduction": "所属项目"},
            {"title": "description", "type": "varchar", "length": 255, "introduction": "备注"},
            {"title": "batch", "type": "varchar", "length": 255, "introduction": "批次"},
            {"title": "relevancy_one", "type": "varchar", "length": 255, "introduction": "关联字段1"},
            {"title": "relevancy_two", "type": "varchar", "length": 255, "introduction": "关联字段2"},
            {"title": "out", "type": "numeric", "length": 0, "introduction": ""}
        ]
    },
    "agri_machine_current_data": {
        "introduction": "农机具当前实时数据表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "device_code", "type": "varchar", "length": 100, "introduction": "设备编码"},
            {"title": "device_type", "type": "varchar", "length": 100, "introduction": "设备类型"},
            {"title": "imei", "type": "varchar", "length": 100, "introduction": "机具识别号"},
            {"title": "longitude", "type": "numeric", "length": 0, "introduction": "经度"},
            {"title": "latitude", "type": "numeric", "length": 0, "introduction": "纬度"},
            {"title": "speed", "type": "numeric", "length": 0, "introduction": "速度(m/s)"},
            {"title": "deepth", "type": "numeric", "length": 0, "introduction": "深度(mm)"},
            {"title": "width", "type": "numeric", "length": 0, "introduction": "宽度(mm)"},
            {"title": "azimuth", "type": "numeric", "length": 0, "introduction": "方位角"},
            {"title": "altitude", "type": "numeric", "length": 0, "introduction": "海拔(m)"},
            {"title": "send_time", "type": "", "length": 0, "introduction": "发送时间(yyyy-MM-dd HH:mm:ss)"},
            {"title": "spray_pressure", "type": "numeric", "length": 0, "introduction": "喷药压力(pa)"},
            {"title": "spray_flow_rate", "type": "numeric", "length": 0, "introduction": "喷药流量(ml/s)"},
            {"title": "humidity", "type": "numeric", "length": 0, "introduction": "湿度(%)"},
            {"title": "temperature", "type": "numeric", "length": 0, "introduction": "温度(℃)"},
            {"title": "crop_name", "type": "varchar", "length": 100, "introduction": "作物名称"},
            {"title": "row_spacing", "type": "numeric", "length": 0, "introduction": "株距(mm)"},
            {"title": "seeding_rate", "type": "numeric", "length": 0, "introduction": "亩均播量(kg)"},
            {"title": "height", "type": "numeric", "length": 0, "introduction": "高度(mm)"}
        ]
    },
    "agri_machine_history_data": {
        "introduction": "农机具历史数据表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "device_code", "type": "varchar", "length": 255, "introduction": "设备编码"},
            {"title": "device_type", "type": "varchar", "length": 255, "introduction": "设备类型"},
            {"title": "imei", "type": "varchar", "length": 255, "introduction": "机具识别号"},
            {"title": "longitude", "type": "numeric", "length": 0, "introduction": "经度"},
            {"title": "latitude", "type": "numeric", "length": 0, "introduction": "纬度"},
            {"title": "speed", "type": "numeric", "length": 0, "introduction": "速度(m/s)"},
            {"title": "deepth", "type": "numeric", "length": 0, "introduction": "深度(mm)"},
            {"title": "width", "type": "numeric", "length": 0, "introduction": "宽度(mm)"},
            {"title": "azimuth", "type": "numeric", "length": 0, "introduction": "方位角"},
            {"title": "altitude", "type": "numeric", "length": 0, "introduction": "海拔(m)"},
            {"title": "send_time", "type": "", "length": 0, "introduction": "发送时间(yyyy-MM-dd HH:mm:ss)"},
            {"title": "spray_pressure", "type": "numeric", "length": 0, "introduction": "喷药压力(pa)"},
            {"title": "spray_flow_rate", "type": "numeric", "length": 0, "introduction": "喷药流量(ml/s)"},
            {"title": "humidity", "type": "numeric", "length": 0, "introduction": "湿度(%)"},
            {"title": "temperature", "type": "numeric", "length": 0, "introduction": "温度(℃)"},
            {"title": "crop_name", "type": "numeric", "length": 0, "introduction": "作物名称"},
            {"title": "row_spacing", "type": "numeric", "length": 0, "introduction": "株距(mm)"},
            {"title": "seeding_rate", "type": "numeric", "length": 0, "introduction": "亩均播量(kg)"},
            {"title": "height", "type": "numeric", "length": 0, "introduction": "高度(mm)"}
        ]
    },
    "agri_machine_job_image_data": {
        "introduction": "农机具历史数据表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "device_code", "type": "varchar", "length": 255, "introduction": "设备编码"},
            {"title": "device_type", "type": "varchar", "length": 255, "introduction": "设备类型"},
            {"title": "imei", "type": "varchar", "length": 255, "introduction": "机具识别号"},
            {"title": "longitude", "type": "numeric", "length": 0, "introduction": "经度"},
            {"title": "latitude", "type": "numeric", "length": 0, "introduction": "纬度"},
            {"title": "image_url", "type": "varchar", "length": 0, "introduction": ""}
        ]
    },
    "agri_machine_job_plot_data": {
        "introduction": "农机具作业地块数据表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "device_code", "type": "varchar", "length": 255, "introduction": "设备编码"},
            {"title": "device_type", "type": "varchar", "length": 255, "introduction": "设备类型"},
            {"title": "imei", "type": "varchar", "length": 255, "introduction": "机具识别号"},
            {"title": "longitude", "type": "numeric", "length": 0, "introduction": "经度"},
            {"title": "latitude", "type": "numeric", "length": 0, "introduction": "纬度"},
            {"title": "plot_area", "type": "numeric", "length": 0, "introduction": "地块面积(m2)"},
            {"title": "job_area", "type": "numeric", "length": 0, "introduction": "作业面积(m2)"},
            {"title": "pass_area", "type": "numeric", "length": 0, "introduction": "合格面积(m2)"},
            {"title": "repeat_area", "type": "numeric", "length": 0, "introduction": "重复面积(m2)"},
            {"title": "job_date", "type": "timestamp", "length": 0, "introduction": "作业时间(yyyy-MM-dd)"},
            {"title": "geom", "type": "geometry", "length": 0, "introduction": ""},
            {"title": "city", "type": "varchar", "length": 15, "introduction": "省"},
            {"title": "district", "type": "varchar", "length": 15, "introduction": "市"},
            {"title": "town", "type": "varchar", "length": 15, "introduction": "县"},
            {"title": "address", "type": "varchar", "length": 255, "introduction": "镇"},
            {"title": "province", "type": "varchar", "length": 15, "introduction": "具体位置"}
        ]
    },
    "assistant_decision_report": {
        "introduction": "辅助决策建议报告表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "item_id", "type": "Int4", "length": 32, "introduction": "所属项目"},
            {"title": "report_name", "type": "varchar", "length": 200, "introduction": "辅助决策建议报告名称"},
            {"title": "report_stage", "type": "varchar", "length": 5, "introduction": "报告适用阶段"},
            {"title": "report_type", "type": "varchar", "length": 5, "introduction": "报告类型"},
            {"title": "crop_name", "type": "varchar", "length": 100, "introduction": "报告适用作物"},
            {"title": "report_file", "type": "varchar", "length": 100, "introduction": "报告文件"},
            {"title": "remarks", "type": "varchar", "length": 255, "introduction": "备注"}
        ]
    },
    "business_use_entity": {
        "introduction": "经营使用主体表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "business_use_entity_name", "type": "varchar", "length": 100, "introduction": "名称"},
            {"title": "business_use_entity_type", "type": "varchar", "length": 50, "introduction": "类型"},
            {"title": "description", "type": "varchar", "length": 255, "introduction": "备注"},
            {"title": "status", "type": "varchar", "length": 20, "introduction": "状态 0启用 1禁用"},
            {"title": "province", "type": "varchar", "length": 255, "introduction": "省"},
            {"title": "city", "type": "varchar", "length": 255, "introduction": "市"},
            {"title": "district", "type": "varchar", "length": 255, "introduction": "县"},
            {"title": "town", "type": "varchar", "length": 255, "introduction": "镇"},
            {"title": "village", "type": "varchar", "length": 255, "introduction": "村"},
            {"title": "item_id", "type": "Int4", "length": 32, "introduction": "所属农场"},
            {"title": "name", "type": "varchar", "length": 30, "introduction": "联系人姓名"},
            {"title": "phone", "type": "varchar", "length": 70, "introduction": "联系手机号"},
            {"title": "account", "type": "varchar", "length": 100, "introduction": "银行账户"},
            {"title": "opening_name", "type": "varchar", "length": 30, "introduction": "开户名"},
            {"title": "opening_bank", "type": "varchar", "length": 50, "introduction": "开户银行"},
            {"title": "farm_land_num", "type": "Int4", "length": 32, "introduction": "农田数量"},
            {"title": "farm_total_area", "type": "numeric", "length": 0, "introduction": "农田总面积"},
            {"title": "farm_standard_area", "type": "numeric", "length": 0, "introduction": "高标准面积"},
            {"title": "farm_other_area", "type": "numeric", "length": 0, "introduction": "其他面积"},
            {"title": "water_quota", "type": "numeric", "length": 0, "introduction": "用水量配额"},
            {"title": "water_cumulative", "type": "numeric", "length": 0, "introduction": "用水量累计"},
            {"title": "electricity", "type": "numeric", "length": 0, "introduction": "电费"},
            {"title": "water_subsidy", "type": "numeric", "length": 0, "introduction": "水补贴"},
            {"title": "water_rewards", "type": "numeric", "length": 0, "introduction": "水奖励"},
            {"title": "procurement", "type": "numeric", "length": 0, "introduction": "采购"},
            {"title": "sell", "type": "numeric", "length": 0, "introduction": "出售"}
        ]
    },
    "data_version": {
        "introduction": "数据版本表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "poll_name", "type": "varchar", "length": 255, "introduction": "权调名称"},
            {"title": "poll_year", "type": "varchar", "length": 255, "introduction": "权调年份"},
            {"title": "description", "type": "varchar", "length": 255, "introduction": "备注"},
            {"title": "status", "type": "int2", "length": 16, "introduction": "状态 0启用 1禁用"}
        ]
    },
    "farm_base_data": {
        "introduction": "基础数据表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "name", "type": "varchar", "length": 100, "introduction": "名称"},
            {"title": "type", "type": "varchar", "length": 10, "introduction": "所属类型"},
            {"title": "categorize_code", "type": "varchar", "length": 50, "introduction": "分类编码(种植作物类型)"},
            {"title": "status", "type": "int2", "length": 16, "introduction": "是否启用  状态 0启用 1禁用"},
            {"title": "is_delete", "type": "", "length": 0, "introduction": ""}
        ]
    },
    "farm_device": {
        "introduction": "物联网设备表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "device_name", "type": "varchar", "length": 155, "introduction": "设备名称"},
            {"title": "device_code", "type": "varchar", "length": 200, "introduction": "设备编码"},
            {"title": "device_type", "type": "varchar", "length": 155, "introduction": "设备类型"},
            {"title": "device_model", "type": "varchar", "length": 155, "introduction": "设备型号"},
            {"title": "device_factory", "type": "varchar", "length": 155, "introduction": "生产厂家"},
            {"title": "device_protocol", "type": "varchar", "length": 155, "introduction": "设备协议"},
            {"title": "province", "type": "varchar", "length": 50, "introduction": "省"},
            {"title": "city", "type": "varchar", "length": 50, "introduction": "市"},
            {"title": "district", "type": "varchar", "length": 50, "introduction": "县"},
            {"title": "town", "type": "varchar", "length": 50, "introduction": "镇"},
            {"title": "item_id", "type": "int4", "length": 32, "introduction": "所属项目id"},
            {"title": "remote_control", "type": "int4", "length": 32, "introduction": "是否支持远程操控 0支持 1不支持"},
            {"title": "device_pic", "type": "Varchar", "length": 100, "introduction": "设备照片"},
            {"title": "status", "type": "int4", "length": 16, "introduction": "启用禁用"},
            {"title": "is_deleted", "type": "int4", "length": 16, "introduction": "删除标记"},
            {"title": "longitude", "type": "numeric", "length": 0, "introduction": "经度"},
            {"title": "latitude", "type": "numeric", "length": 0, "introduction": "纬度"},
            {"title": "description", "type": "varchar", "length": 100, "introduction": "备注"},
            {"title": "sip_serverid", "type": "varchar", "length": 100, "introduction": "sip服务器ID"},
            {"title": "sip_region", "type": "varchar", "length": 100, "introduction": "sip服务器域"},
            {"title": "sip_ip", "type": "varchar", "length": 100, "introduction": "sip服务器地址"},
            {"title": "sip_port", "type": "varchar", "length": 100, "introduction": "sip服务器端口"},
            {"title": "sip_username", "type": "varchar", "length": 100, "introduction": "sip用户名"},
            {"title": "sip_authid", "type": "varchar", "length": 100, "introduction": "sip用户认证ID"},
            {"title": "sip_passage_code", "type": "varchar", "length": 100, "introduction": "视频通道编码ID"},
            {"title": "video_url", "type": "varchar", "length": 100, "introduction": "视频播放地址"},
            {"title": "is_online", "type": "varchar", "length": 100, "introduction": "是否在线 0在线 1离线"},
            {"title": "address", "type": "varchar", "length": 100, "introduction": "详细地址"},
            {"title": "plot_code", "type": "varchar", "length": 100, "introduction": "种植地块编码"},
            {"title": "origin_type", "type": "varchar", "length": 100, "introduction": "数据来源 1系统添加  2外部接口同步"}
        ]
    },
    "farm_device_data": {
        "introduction": "物联网设备数据表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "device_code", "type": "varchar", "length": 255, "introduction": "设备编码"},
            {"title": "device_type", "type": "varchar", "length": 20, "introduction": "设备类型"},
            {"title": "item_id", "type": "Int4", "length": 32, "introduction": "所属项目id"},
            {"title": "shard_field", "type": "varchar", "length": 255, "introduction": "device_type"},
            {"title": "md5", "type": "varchar", "length": 255, "introduction": "数据校验值"},
            {"title": "original_data", "type": "text", "length": 0, "introduction": "原始数据"},
            {"title": "weather", "type": "varchar", "length": 255, "introduction": "天气"},
            {"title": "air_temperature", "type": "numeric", "length": 0, "introduction": "气温（℃）"},
            {"title": "wind_speed", "type": "numeric", "length": 0, "introduction": "风速（m/s）"},
            {"title": "air_humidity", "type": "numeric", "length": 0, "introduction": "湿度（%）"},
            {"title": "precipitation", "type": "numeric", "length": 0, "introduction": "降水量"},
            {"title": "aqi", "type": "numeric", "length": 0, "introduction": "air quality index 空气质量指数"},
            {"title": "wind_direction", "type": "varchar", "length": 32, "introduction": "风向"},
            {"title": "air_pressure", "type": "numeric", "length": 0, "introduction": "气压（kPa）"},
            {"title": "illuminance", "type": "numeric", "length": 0, "introduction": "光照度-日照（Lux）"},
            {"title": "pest_type", "type": "varchar", "length": 255, "introduction": "害虫类型"},
            {"title": "pest_num", "type": "Int4", "length": 32, "introduction": "害虫数量"},
            {"title": "spore_type", "type": "Varchar", "length": 255, "introduction": "孢子类型"},
            {"title": "spore_num", "type": "Int4", "length": 32, "introduction": "孢子数量"},
            {"title": "soil_temperature", "type": "numeric", "length": 0, "introduction": "土壤温度（℃）"},
            {"title": "soil_humidity", "type": "numeric", "length": 0, "introduction": "土壤湿度（%）"},
            {"title": "soil_ph", "type": "numeric", "length": 0, "introduction": "土壤PH 值"},
            {"title": "soil_conductivity", "type": "numeric", "length": 0, "introduction": "土壤电导率（ms/cm）"},
            {"title": "year", "type": "varchar", "length": 255, "introduction": "年份"},
            {"title": "month", "type": "varchar", "length": 255, "introduction": "月份"},
            {"title": "record_time", "type": "timestamp", "length": 6, "introduction": "采集时间"},
            {"title": "soil_temperature2", "type": "numeric", "length": 0, "introduction": "土壤温度（℃）"},
            {"title": "soil_temperature3", "type": "numeric", "length": 0, "introduction": "土壤温度（℃）"},
            {"title": "soil_humidity2", "type": "numeric", "length": 0, "introduction": "土壤湿度（%）"},
            {"title": "soil_humidity3", "type": "numeric", "length": 0, "introduction": "土壤湿度（%）"},
            {"title": "soil_conductivity2", "type": "numeric", "length": 0, "introduction": "土壤电导率（ms/cm）"},
            {"title": "soil_conductivity3", "type": "numeric", "length": 0, "introduction": "土壤电导率（ms/cm）"},
            {"title": "soil_ph2", "type": "numeric", "length": 0, "introduction": "土壤PH 值"},
            {"title": "soil_ph3", "type": "numeric", "length": 0, "introduction": "土壤PH 值"},
            {"title": "create_report", "type": "varchar", "length": 255, "introduction": "是否生成农情分析报告  0已生成  1未生成"},
            {"title": "pest", "type": "jsonb", "length": 0, "introduction": "害虫"},
            {"title": "spore", "type": "jsonb", "length": 0, "introduction": "孢子"},
            {"title": "pest_file", "type": "varchar", "length": 255, "introduction": "害虫文件"},
            {"title": "spore_file", "type": "varchar", "length": 255, "introduction": "孢子文件"},
            {"title": "is_online", "type": "Int4", "length": 32, "introduction": "是否在线 0在线 1离线"}
        ]
    },
    "farm_device_warning_info": {
        "introduction": "物联网设备告警数据表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "device_name", "type": "varchar", "length": 255, "introduction": "设备名称"},
            {"title": "device_code", "type": "varchar", "length": 255, "introduction": "设备代码"},
            {"title": "device_type", "type": "varchar", "length": 255, "introduction": "设备类型"},
            {"title": "province", "type": "varchar", "length": 255, "introduction": "省份"},
            {"title": "city", "type": "varchar", "length": 255, "introduction": "市"},
            {"title": "district", "type": "varchar", "length": 255, "introduction": "县"},
            {"title": "town", "type": "varchar", "length": 255, "introduction": "镇"},
            {"title": "item_id", "type": "", "length": 0, "introduction": "所属项目"},
            {"title": "land_code", "type": "varchar", "length": 255, "introduction": "土地代码"},
            {"title": "warning_type", "type": "varchar", "length": 255, "introduction": "警告类型"},
            {"title": "warning_msg", "type": "Text", "length": 0, "introduction": "警告消息"},
            {"title": "standard_value", "type": "varchar", "length": 255, "introduction": "标准值"},
            {"title": "shard_field", "type": "varchar", "length": 255, "introduction": "分片字段"},
            {"title": "create_report", "type": "varchar", "length": 5, "introduction": "是否生成农情分析报告  0已生成  1未生成"},
            {"title": "deal_status", "type": "varchar", "length": 5, "introduction": "是否处理 1未处理  2已安排任务  3已忽略  4已处理"}
        ]
    },
    "farm_item": {
        "introduction": "农场项目表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "item_name", "type": "Int4", "length": 32, "introduction": "所属项目"},
            {"title": "province", "type": "varchar", "length": 255, "introduction": "省"},
            {"title": "city", "type": "varchar", "length": 255, "introduction": "市"},
            {"title": "district", "type": "varchar", "length": 255, "introduction": "县"},
            {"title": "town", "type": "varchar", "length": 255, "introduction": "镇"},
            {"title": "status", "type": "Int4", "length": 32, "introduction": "状态 0启用 1禁用"},
            {"title": "description", "type": "varchar", "length": 255, "introduction": "备注"},
            {"title": "longitude", "type": "Numeric", "length": 0, "introduction": ""},
            {"title": "latitude", "type": "Numeric", "length": 0, "introduction": ""}
        ]
    },
    "farm_job_info": {
        "introduction": "作业记录信息表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "remarks", "type": "varchar", "length": 200, "introduction": "备注"},
            {"title": "plot_code", "type": "varchar", "length": 200, "introduction": "种植地块"},
            {"title": "item_id", "type": "Int4", "length": 32, "introduction": "所属项目"},
            {"title": "business_entity_id", "type": "Int4", "length": 32, "introduction": "所属经营主体id"},
            {"title": "business_entity_type", "type": "varchar", "length": 5, "introduction": "所属经营主体类型"},
            {"title": "job_date", "type": "", "length": 0, "introduction": "作业日期"},
            {"title": "work_type", "type": "varchar", "length": 5, "introduction": "作业类型"},
            {"title": "work_project", "type": "varchar", "length": 5, "introduction": "作业项目"},
            {"title": "crop_name", "type": "varchar", "length": 5, "introduction": "作物名称"},
            {"title": "crop_variety", "type": "varchar", "length": 5, "introduction": "作物品种"},
            {"title": "job_area", "type": "", "length": 0, "introduction": "工作量（亩）"},
            {"title": "job_user", "type": "varchar", "length": 5, "introduction": "填报人"},
            {"title": "job_record_type", "type": "varchar", "length": 5, "introduction": "记录类型"},
            {"title": "job_content", "type": "text", "length": 0, "introduction": "作业内容"},
            {"title": "job_plot_num", "type": "Int4", "length": 16, "introduction": "作业地块数量"},
            {"title": "accurate_task_id", "type": "Int4", "length": 16, "introduction": "关联的精准执行任务id"},
            {"title": "production", "type": "Numeric", "length": 0, "introduction": "产量"}
        ]
    },
    "farm_job_formulation": {
        "introduction": "作业记录-配方信息表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "accurate_task_id", "type": "int4", "length": 32, "introduction": "关联的精准执行任务id"},
            {"title": "formulation_id", "type": "int4", "length": 32, "introduction": "配方id"},
            {"title": "material_id", "type": "int4", "length": 32, "introduction": "物资id"},
            {"title": "item_id", "type": "int4", "length": 32, "introduction": "所属项目id"},
            {"title": "type", "type": "varchar", "length": 255, "introduction": "物资类型 1农药  2肥料 3种子 4农机作业 5水费 6电费"},
            {"title": "plan_usage_mu", "type": "numeric", "length": 0, "introduction": "方案亩用量（公斤）"},
            {"title": "actual_usage_mu", "type": "numeric", "length": 0, "introduction": "实际亩用量（公斤）"},
            {"title": "actual_usage_total", "type": "numeric", "length": 0, "introduction": "实际总用量（公斤）"},
            {"title": "batch_code", "type": "varchar", "length": 255, "introduction": "批次编号"},
            {"title": "material_price", "type": "numeric", "length": 0, "introduction": "物资单价"},
            {"title": "energy_type", "type": "varchar", "length": 255, "introduction": "农机类型 1传统  2新能源"},
            {"title": "labor_cost", "type": "numeric", "length": 0, "introduction": "总数-人工费（元）"},
            {"title": "mechanical_cost", "type": "numeric", "length": 0, "introduction": "总数-机械费（元）"},
            {"title": "oil_cost", "type": "numeric", "length": 0, "introduction": "总数-油费（元）"},
            {"title": "electric_cost", "type": "numeric", "length": 0, "introduction": "总数-电费（元）"},
            {"title": "water_cost", "type": "numeric", "length": 0, "introduction": "总数-水费（元)"},
            {"title": "electric_price", "type": "numeric", "length": 0, "introduction": "单价-电费（元/度）"},
            {"title": "remark", "type": "varchar", "length": 255, "introduction": "备注"},
            {"title": "job_id", "type": "Int4", "length": 32, "introduction": "作业记录id"},
            {"title": "crop_id", "type": "Int4", "length": 32, "introduction": "作物名称"}
        ]
    },
    "farm_plant_plot_info": {
        "introduction": "农场种植地块表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "plot_id", "type": "Int4", "length": 32, "introduction": "冗余地块id = id"},
            {"title": "plot_name", "type": "varchar", "length": 255, "introduction": "种植地块名称"},
            {"title": "plot_code", "type": "varchar", "length": 255, "introduction": "种植地块编码"},
            {"title": "data_version", "type": "varchar", "length": 255, "introduction": "数据版本"},
            {"title": "province", "type": "varchar", "length": 255, "introduction": "省"},
            {"title": "city", "type": "varchar", "length": 255, "introduction": "市"},
            {"title": "district", "type": "varchar", "length": 255, "introduction": "县"},
            {"title": "town", "type": "varchar", "length": 255, "introduction": "镇"},
            {"title": "item_id", "type": "Int4", "length": 32, "introduction": "所属项目id"},
            {"title": "irrigation_id", "type": "Int4", "length": 32, "introduction": "所属轮灌分组id"},
            {"title": "high_land_status", "type": "varchar", "length": 255, "introduction": "高标准农田状态"},
            {"title": "land_code", "type": "varchar", "length": 255, "introduction": "所属宗地编码"},
            {"title": "total_area", "type": "numeric", "length": 0, "introduction": "总面积/录入面积（㎡）"},
            {"title": "draw_area", "type": "numeric", "length": 0, "introduction": "绘图面积（㎡）"},
            {"title": "plot_properties", "type": "varchar", "length": 255, "introduction": "地块性质"},
            {"title": "current_crop", "type": "varchar", "length": 255, "introduction": "当季作物"},
            {"title": "previous_crop", "type": "varchar", "length": 255, "introduction": "上一茬作物"},
            {"title": "business_use_entity_id", "type": "Int4", "length": 32, "introduction": "经营使用主体id"},
            {"title": "info_type", "type": "varchar", "length": 255, "introduction": "信息类别"},
            {"title": "business_use_entity_type", "type": "varchar", "length": 255, "introduction": "经营使用主体类型"},
            {"title": "contract_code", "type": "varchar", "length": 255, "introduction": "承包合同编号"},
            {"title": "contract_amount", "type": "numeric", "length": 0, "introduction": "合同金额(元)"},
            {"title": "contract_start_time", "type": "", "length": 0, "introduction": "承包开始时间"},
            {"title": "contract_end_time", "type": "", "length": 0, "introduction": "承包结束时间"},
            {"title": "geom", "type": "geometry", "length": 0, "introduction": ""},
            {"title": "lon", "type": "numeric", "length": 0, "introduction": ""},
            {"title": "lat", "type": "numeric", "length": 0, "introduction": ""},
            {"title": "remark", "type": "varchar", "length": 255, "introduction": ""},
            {"title": "land_id", "type": "Int4", "length": 32, "introduction": "宗地信息表id"},
            {"title": "land_use_type", "type": "varchar", "length": 255, "introduction": "土地利用类型"},
            {"title": "variety", "type": "Int4", "length": 32, "introduction": "品种"},
            {"title": "is_normal", "type": "varchar", "length": 255, "introduction": "是否正常 0正常  1不正常有病虫害等"},
            {"title": "address", "type": "varchar", "length": 255, "introduction": "坐落"}
        ]
    },
    "formulation": {
        "introduction": "配方信息表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "formulation_name", "type": "varchar", "length": 255, "introduction": "配方名称"},
            {"title": "status", "type": "int4", "length": 32, "introduction": ""},
            {"title": "manure_id", "type": "varchar", "length": 255, "introduction": "肥料名称"},
            {"title": "item_id", "type": "int4", "length": 32, "introduction": "所属项目"},
            {"title": "pesticide_id", "type": "varchar", "length": 255, "introduction": "农药名称"},
            {"title": "job_id", "type": "int4", "length": 32, "introduction": "作业类型"},
            {"title": "crop_id", "type": "int4", "length": 32, "introduction": "作物"},
            {"title": "remark", "type": "varchar", "length": 255, "introduction": "备注"}
        ]
    },
    "land_base_info_management": {
        "introduction": "宗地信息表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "land_id", "type": "Int4", "length": 32, "introduction": "宗地id冗余字段"},
            {"title": "data_version", "type": "varchar", "length": 255, "introduction": "数据版本"},
            {"title": "land_code", "type": "varchar", "length": 255, "introduction": "宗地编码"},
            {"title": "land_use_type", "type": "varchar", "length": 255, "introduction": "土地利用类型"},
            {"title": "land_use_type2", "type": "varchar", "length": 255, "introduction": "土地利用类型2"},
            {"title": "business_and_use_type", "type": "varchar", "length": 255, "introduction": "经营使用主体类型"},
            {"title": "business_and_use_name", "type": "varchar", "length": 255, "introduction": "经营使用主体名称"},
            {"title": "total_area", "type": "Numeric", "length": 0, "introduction": "总面积/录入面积（㎡）"},
            {"title": "draw_area", "type": "Numeric", "length": 0, "introduction": "绘图面积（㎡）"},
            {"title": "tenure_status", "type": "varchar", "length": 255, "introduction": "权属状态"},
            {"title": "three_type", "type": "varchar", "length": 255, "introduction": "所属三大类"},
            {"title": "info_type", "type": "varchar", "length": 255, "introduction": "信息类别"},
            {"title": "info_type2", "type": "varchar", "length": 255, "introduction": "信息类别2 中间字段"},
            {"title": "is_deleted", "type": "Int2", "length": 32, "introduction": "是否删除  0没有删除  1删除"},
            {"title": "description", "type": "varchar", "length": 255, "introduction": "备注"},
            {"title": "land_name", "type": "varchar", "length": 255, "introduction": "宗地俗名"},
            {"title": "longitude", "type": "numeric", "length": 0, "introduction": "经度 输入值"},
            {"title": "latitude", "type": "numeric", "length": 0, "introduction": "纬度 输入值"},
            {"title": "plot_code", "type": "varchar", "length": 255, "introduction": "地块编码"},
            {"title": "certificate_area", "type": "varchar", "length": 255, "introduction": "证书面积（㎡）"},
            {"title": "certificate_type", "type": "varchar", "length": 255, "introduction": "权证类型"},
            {"title": "certificate_code", "type": "varchar", "length": 255, "introduction": "权属证号"},
            {"title": "certificate_pic", "type": "varchar", "length": 255, "introduction": "证书照片/文件 新版本"},
            {"title": "address", "type": "varchar", "length": 255, "introduction": "坐落"},
            {"title": "issuing_authority", "type": "varchar", "length": 255, "introduction": "发证机关"},
            {"title": "regist_date", "type": "date", "length": 0, "introduction": "登记日期"},
            {"title": "certificate_num", "type": "varchar", "length": 255, "introduction": "证书编号"},
            {"title": "landuse_rights_owners", "type": "varchar", "length": 255, "introduction": "证载权利人/土地使用权人"},
            {"title": "jointly_owned_status", "type": "varchar", "length": 255, "introduction": "共有情况"},
            {"title": "real_estate_number", "type": "varchar", "length": 255, "introduction": "不动产单元号/地号"},
            {"title": "right_type", "type": "varchar", "length": 255, "introduction": "权利类型"},
            {"title": "right_properties", "type": "varchar", "length": 255, "introduction": "权利性质/使用权类型"},
            {"title": "land_type", "type": "varchar", "length": 255, "introduction": "地类（用途）"},
            {"title": "certificate_start_time", "type": "date", "length": 0, "introduction": "权属起始日期"},
            {"title": "certificate_end_time", "type": "date", "length": 0, "introduction": "权属终止日期"},
            {"title": "remarks", "type": "varchar", "length": 255, "introduction": "附记"},
            {"title": "certificate_descr", "type": "varchar", "length": 255, "introduction": "权证备注"},
            {"title": "geom", "type": "geometry", "length": 0, "introduction": ""},
            {"title": "lon", "type": "numeric", "length": 0, "introduction": "经度 系统生成"},
            {"title": "lat", "type": "numeric", "length": 0, "introduction": "纬度 系统生成"},
            {"title": "certificate_pic_old", "type": "varchar", "length": 255, "introduction": "证书照片/文件 老版本"},
            {"title": "land_code_old", "type": "varchar", "length": 255, "introduction": "宗地编码 老版本"},
            {"title": "flag", "type": "varchar", "length": 255, "introduction": ""},
            {"title": "item_id", "type": "int4", "length": 32, "introduction": ""},
            {"title": "rotational_id", "type": "int4", "length": 32, "introduction": "轮灌分组id"},
            {"title": "land_status", "type": "varchar", "length": 255, "introduction": "高标准农田状态"},
            {"title": "province", "type": "varchar", "length": 255, "introduction": ""},
            {"title": "city", "type": "varchar", "length": 255, "introduction": ""},
            {"title": "district", "type": "varchar", "length": 255, "introduction": ""},
            {"title": "town", "type": "varchar", "length": 255, "introduction": ""},
            {"title": "land_type_code", "type": "varchar", "length": 255, "introduction": "分类编码"},
            {"title": "business_and_use_id", "type": "int4", "length": 32, "introduction": "经营主体id"},
            {"title": "item_id_bak", "type": "int4", "length": 32, "introduction": ""},
            {"title": "is_demonstration_field", "type": "varchar", "length": 255, "introduction": "是否是示范田 0是  1否"}
        ]
    },
    "manure": {
        "introduction": "肥料信息表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "manure_type", "type": "varchar", "length": 255, "introduction": "肥料形态"},
            {"title": "status", "type": "int4", "length": 32, "introduction": ""},
            {"title": "manure_name", "type": "varchar", "length": 255, "introduction": "肥料通用名称(类型)"},
            {"title": "item_id", "type": "int4", "length": 32, "introduction": "所属项目"},
            {"title": "content", "type": "varchar", "length": 255, "introduction": "技术指标"},
            {"title": "prod_name", "type": "varchar", "length": 255, "introduction": "产品名称"}
        ]
    },
    "meteorological_info": {
        "introduction": "气象数据表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "item_id", "type": "Int4", "length": 32, "introduction": "所属项目"},
            {"title": "meteorological_data_type", "type": "varchar", "length": 10, "introduction": "数据类型"},
            {"title": "collection_time", "type": "timestamp", "length": 6, "introduction": "数据采集时间"}
        ]
    },
    "meteorological_warning": {
        "introduction": "气象告警数据表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "item_id", "type": "int4", "length": 32, "introduction": "所属项目"},
            {"title": "warning_time", "type": "timestamp", "length": 6, "introduction": "告警时间"},
            {"title": "warning_type", "type": "varchar", "length": 255, "introduction": "告警类型"},
            {"title": "warning_land", "type": "varchar", "length": 255, "introduction": "告警地块"},
            {"title": "warning_data", "type": "varchar", "length": 255, "introduction": "告警数据"},
            {"title": "crop_data", "type": "varchar", "length": 255, "introduction": "当前作物适用数据"},
            {"title": "device_code", "type": "varchar", "length": 255, "introduction": "设备编码"}
        ]
    },
    "patrol_field_info": {
        "introduction": "人工巡田信息表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "province", "type": "varchar", "length": 255, "introduction": ""},
            {"title": "city", "type": "varchar", "length": 255, "introduction": ""},
            {"title": "district", "type": "varchar", "length": 255, "introduction": ""},
            {"title": "town", "type": "varchar", "length": 255, "introduction": ""},
            {"title": "item_id", "type": "int4", "length": 32, "introduction": ""},
            {"title": "patrol_time", "type": "timestamp", "length": 6, "introduction": "巡田日期"},
            {"title": "patrol_person", "type": "varchar", "length": 255, "introduction": "巡田人"},
            {"title": "crop_name", "type": "varchar", "length": 255, "introduction": "作物名称"},
            {"title": "crop_variety", "type": "varchar", "length": 255, "introduction": "作物品种"},
            {"title": "crop_code", "type": "varchar", "length": 255, "introduction": "作物品种编号"},
            {"title": "growth_cycle", "type": "varchar", "length": 255, "introduction": "作物生长期"},
            {"title": "plot_code", "type": "varchar", "length": 255, "introduction": "数据采集位置-地块编码"},
            {"title": "patrol_pic", "type": "varchar", "length": 255, "introduction": "巡田照片"},
            {"title": "soil_temperature", "type": "numeric", "length": 0, "introduction": "土壤温度"},
            {"title": "soil_humidity", "type": "numeric", "length": 0, "introduction": "土壤湿度"},
            {"title": "n", "type": "numeric", "length": 0, "introduction": "氮含量"},
            {"title": "p", "type": "numeric", "length": 0, "introduction": "磷含量"},
            {"title": "k", "type": "numeric", "length": 0, "introduction": "钾含量"},
            {"title": "ph", "type": "numeric", "length": 0, "introduction": "PH值"},
            {"title": "om", "type": "numeric", "length": 0, "introduction": "有机质含量"},
            {"title": "soil_conductivity", "type": "numeric", "length": 0, "introduction": "土壤电导率"},
            {"title": "soil_other", "type": "varchar", "length": 255, "introduction": "其他"},
            {"title": "leaf_length", "type": "numeric", "length": 0, "introduction": "叶长"},
            {"title": "leaf_width", "type": "numeric", "length": 0, "introduction": "叶宽"},
            {"title": "stem_girth", "type": "numeric", "length": 0, "introduction": "茎粗"},
            {"title": "leaf_num", "type": "Int4", "length": 32, "introduction": "叶片数量"},
            {"title": "plant_height", "type": "numeric", "length": 0, "introduction": "株高"},
            {"title": "spike_position", "type": "varchar", "length": 255, "introduction": "穗位度"},
            {"title": "spike_length", "type": "numeric", "length": 0, "introduction": "穗长"},
            {"title": "spike_width", "type": "numeric", "length": 0, "introduction": "穗宽"},
            {"title": "spike_head", "type": "varchar", "length": 255, "introduction": "穗头"},
            {"title": "spike_num", "type": "", "length": 0, "introduction": "穗位数"},
            {"title": "hundred_grains_weight", "type": "numeric", "length": 0, "introduction": "百粒重"},
            {"title": "stem_rot", "type": "varchar", "length": 255, "introduction": "茎腐"},
            {"title": "empty_pole_ratio", "type": "numeric", "length": 0, "introduction": "空杆率"},
            {"title": "thresh_water_content", "type": "numeric", "length": 0, "introduction": "脱粒时含水量"},
            {"title": "leaf_n", "type": "numeric", "length": 0, "introduction": "叶片含氮量"},
            {"title": "leaf_other", "type": "varchar", "length": 255, "introduction": "其他"},
            {"title": "remarks", "type": "varchar", "length": 255, "introduction": ""},
            {"title": "business_use_entity_type", "type": "varchar", "length": 255, "introduction": "经营主体类型"},
            {"title": "business_use_entity_id", "type": "int4", "length": 32, "introduction": "经营主体id"},
            {"title": "detect_device", "type": "varchar", "length": 255, "introduction": "检测设备"},
            {"title": "longitude", "type": "numeric", "length": 0, "introduction": ""},
            {"title": "latitude", "type": "numeric", "length": 0, "introduction": ""},
            {"title": "year", "type": "varchar", "length": 255, "introduction": ""},
            {"title": "plot_name", "type": "varchar", "length": 255, "introduction": "地块名称"}
        ]
    },
    "pesticide": {
        "introduction": "农资信息表",
        "fields": [
            {"title": "id", "type": "int4", "length": 32, "introduction": "主键id"},
            {"title": "create_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "update_time", "type": "timestamp", "length": 6, "introduction": ""},
            {"title": "create_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "update_user", "type": "varchar", "length": 15, "introduction": ""},
            {"title": "pesticide_type", "type": "varchar", "length": 255, "introduction": "农药类型"},
            {"title": "status", "type": "int4", "length": 32, "introduction": ""},
            {"title": "pesticide_name", "type": "varchar", "length": 255, "introduction": "农药名称"},
            {"title": "item_id", "type": "int4", "length": 32, "introduction": "所属项目"},
            {"title": "content", "type": "varchar", "length": 255, "introduction": "含量"},
            {"title": "pesticide_formulations", "type": "varchar", "length": 255, "introduction": "农药剂型"}
        ]
    }
}

fuxi_keywords_table_list = [
  {
    "key": "地块",
    "tables": [
      {"name": "farm_plant_plot_info", "introduction": "农场种植地块表"},
      {"name": "land_base_info_management", "introduction": "宗地信息表"},
      {"name": "agri_machine_job_plot_data", "introduction": "农机具作业地块数据表"}
    ]
  },
  {
    "key": "土壤",
    "tables": [
      {"name": "farm_device_data", "introduction": "物联网设备数据表（包含土壤温度、湿度等数据）"},
      {"name": "patrol_field_info", "introduction": "人工巡田信息表（包含土壤检测数据）"}
    ]
  },
  {
    "key": "种子",
    "tables": [
      {"name": "seed_bank_info", "introduction": "种子库管理表"},
      {"name": "seed_bank_attribute", "introduction": "种子库字段属性表"},
      {"name": "seed_bank_value", "introduction": "种子库播种/生长周期条件表"}
    ]
  },
  {
    "key": "处方",
    "tables": [
      {"name": "formulation", "introduction": "配方信息表"},
      {"name": "accurate_execute_task_info", "introduction": "精准执行任务信息表（包含处方图信息）"}
    ]
  },
  {
    "key": "农机",
    "tables": [
      {"name": "agricultural", "introduction": "农机信息表"},
      {"name": "agri_machine_current_data", "introduction": "农机具当前实时数据表"},
      {"name": "agri_machine_history_data", "introduction": "农机具历史数据表"}
    ]
  },
  {
    "key": "气象",
    "tables": [
      {"name": "meteorological_info", "introduction": "气象数据表"},
      {"name": "meteorological_warning", "introduction": "气象告警数据表"},
      {"name": "farm_device_data", "introduction": "物联网设备数据表（包含气象数据）"}
    ]
  },
  {
    "key": "种植",
    "tables": [
      {"name": "farm_plant_plot_info", "introduction": "农场种植地块表"},
      {"name": "seed_bank_info", "introduction": "种子库管理表"},
      {"name": "farm_job_info", "introduction": "作业记录信息表"},
      {"name": "farm_base_data", "introduction": "基础数据表(包含当前种植信息, catalog_code 存种植作物名称)"}
    ]
  },
  {
    "key": "检测",
    "tables": [
      {"name": "patrol_field_info", "introduction": "人工巡田信息表"},
      {"name": "farm_device_data", "introduction": "物联网设备数据表"}
    ]
  },
  {
    "key": "决策",
    "tables": [
      {"name": "assistant_decision_report", "introduction": "辅助决策建议报告表"},
      {"name": "agri_analysis_report", "introduction": "农情分析报告表"}
    ]
  },
  {
    "key": "经营主体",
    "tables": [
      {"name": "business_use_entity", "introduction": "经营使用主体表"},
      {"name": "land_base_info_management", "introduction": "宗地信息表（包含经营主体信息）"}
    ]
  },
]
